// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD91X1GJ1h4MBusi8Kg2y1el6EsVJ4DHTw',
    appId: '1:345893578855:web:4e299e379b90d619d5ccc2',
    messagingSenderId: '345893578855',
    projectId: 'u-learning-442ec',
    authDomain: 'u-learning-442ec.firebaseapp.com',
    storageBucket: 'u-learning-442ec.appspot.com',
    measurementId: 'G-J71EVEVBV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWv41KYtu5VgP0gdVg2iOLw3DfdKcB3-s',
    appId: '1:345893578855:android:6c4467a05e319118d5ccc2',
    messagingSenderId: '345893578855',
    projectId: 'u-learning-442ec',
    storageBucket: 'u-learning-442ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-UwdfnYfDaduK_-RSCUDTwUaEnD33r18',
    appId: '1:345893578855:ios:a9cc9d254eede06ed5ccc2',
    messagingSenderId: '345893578855',
    projectId: 'u-learning-442ec',
    storageBucket: 'u-learning-442ec.appspot.com',
    iosBundleId: 'com.example.uLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-UwdfnYfDaduK_-RSCUDTwUaEnD33r18',
    appId: '1:345893578855:ios:a9cc9d254eede06ed5ccc2',
    messagingSenderId: '345893578855',
    projectId: 'u-learning-442ec',
    storageBucket: 'u-learning-442ec.appspot.com',
    iosBundleId: 'com.example.uLearning',
  );
}
